### ISSUE TITLE
Chrome/iOS - no scroll control

### ISSUE THREAD

**Issue by wondermoi** [tiddlydrive/tiddlydrive.github.io#38] opened 2021-08-14 13:21 UTC
Hi Tiddlydrive community !

I'm kind of a newbie in the wonderful Tiddly world since I've just been using it for a few days on my PC, saving my file on Google drive thanks to TiddlyDrive. As I am pretty motivated by making the most of this note taking concept anywhere, anytime, I'd like to use it on my mobile phone too. Yesterday, I found out that opening a direct tiddlydrive link in Chrome for iOS had granted me access to my notebook but only to what I could be seen on the phone screen, leaving no opportunity to scroll down and access the whole page.

Is there any setting that I'd missed or would it be an issue to submit ?

Thanks for your help.

Sandrine

**Comment by LordRatte** [comment] 2021-08-16 04:18
This seems like a duplicate of issue #3 . I cannot reliably test anything on Apple products because I don't own any. This has to wait until someone with an Apple product is wiling to debug it.

**Closed by LordRatte** 2021-08-16 04:18 UTC

**Comment by wondermoi** [comment] 2021-08-16 17:13
Thanks for your reply... another good reason to switch to Android ;-) !!
